### ISSUE TITLE
Question about align_uniform.py

### ISSUE THREAD

**Issue by SeunghanYu** [sfarhat/dapt#1]
Hello, @sfarhat !

I noticed that the uniform_loss function in align_uniform.py at line 21 includes a .log() at the end, which differs from the implementation described in the paper.

Paper:
![image](https://github.com/sfarhat/dapt/assets/128061514/3070f11e-2911-4e69-9b8f-a90776ccb094)

Code:
```
def uniform_loss(self, x, t=2):
    return torch.pdist(x, p=2).pow(2).mul(-t).exp().mean().log()
```

Could you explain the reason for using .log() in this context?

**Comment by sfarhat** [comment]
Hello @SeunghanYu, thank you for catching this! This is a typo in the paper, but the code is correct; for the uniformity loss, a logarithm should wrap around the expectation, similar to the [original Align/Uniform paper](https://arxiv.org/pdf/2005.10242.pdf). 

I'll upload a new version of the paper with this fix to arXiv soon.
